services:
  php-env:
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:80"
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fisicaonline
    ports:
      - "3307:3306" # Mapeia a porta 3307 para a porta interna 3306 do container

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "9001:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306 # Internamente, o phpMyAdmin conecta na porta padrão do container MySQL
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql_db
